### ISSUE TITLE
Clarify what types of files OSACA takes

### ISSUE THREAD

**Issue by travisdowns** [RRZE-HPC/OSACA#37]
I admit after reading the documentation a couple of times, it is not clear to me what types of files OSACA should take. IACA takes only binaries (AFAIK), so I had assumed it is binaries, but it seems like you can do source level annotations of C files like `//STARTLOOP` so then I kind of assumed you feed in a source file, but then how it is going to get the binary (I assume you don't compile under the covers).

I think the answer is that OSACA also only takes binary files, but then it does some magic using debug info to map back to source files and loop for markers, but I think the documentation could maybe be a bit more explicit (and mention the requirement to use `-g` since by default a lot of people won't).

**Comment by JanLJL** [comment]
For version 0.3, which is still under development, the README file was not adjusted yet.
You cannot add high level markers anymore, but only byte markers in the assembly. For analysing the loop kernel, you **don't** have to compile the assembly code to a binary!
I updated the README file in cd5f131 so you can find the exact markers and explanations to the usage and will extend it with more examples and newer workflow graphs soon.

If something is still unclear, let me know!

**Comment by travisdowns** [comment]
@JanLJL  - thanks for the update.

Do I understand correctly that OSACA *only* accepts textual assembly now, not binaries? I looked at the new README but it is still not totally clear.

It would be nice to comment on the expected format of the assembly: for example, Intel syntax is common for people who write assembly in x86, perhaps more common than [g]as syntax, but I think [g]as (i.e., AT&T plus gas extensions) is being used? 

For the byte markers, is OSACA making a textual match against the markers, or does it do some kind of assembly and then look at the bytes? For example, I define by markers as

```
%define IACA_START db 0xbb, 0x6f, 0, 0, 0, 0x64, 0x67, 0x90
```

(this is nasm syntax, but you can imagine the gas equivalent)

So the actual marker in the code is just IACA_START - would it work (ignoring I guess for now the problem of nasm-like input).

**Comment by travisdowns** [comment]
> For now you need your compiler to output the high level code as GAS syntax or compile your Intel syntax assembly and disassemble it again as GAS.

Thanks. The second approach is the best I think (I often write directly in assembly, so just getting the compiler to emit AT&T syntax doesn't work, but a compile -> decompile is totally feasible. Of course, it still means I have to understand the OSACA output in AT&T syntax (I can, but it involves mentally reversing everything).

Is AT&T output the standard in the HPC space? From what I can tell Intel syntax is popular in most performance analysis communities and documents, although I have seen a lot of AT&T in HPC related papers.

**Comment by cod3monk** [comment]
> Is AT&T output the standard in the HPC space? 
No, but it was a design choice in the beginning, as it is the default output for x86 by GCC and LLVM.

**Comment by travisdowns** [comment]
@cod3monk - yes, go ahead!
